# Generated by Django 4.1.5 on 2023-01-24 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="address1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.TextField(default="address"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 10, 14, 4, 189408)
            ),
        ),
    ]
