# Generated by Django 4.1.5 on 2023-01-24 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_comment_address1_comment_name_alter_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 24, 10, 15, 32, 57192)
            ),
        ),
    ]
